[versions]
junit-jupiter = "5.9.1"
guava = "31.1-jre"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
