/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.demo;

public class App {

    public static void main(String[] args) {
        System.out.println(
                Constants.GREETING
        );
    }
}
